Vagrant.configure("2") do |config|
  config.vm.box_check_update = false
  config.vm.boot_timeout = 600  
  
  # Máquina virtual externa con Kali Linux
  config.vm.define "external-kali" do |kali|
    kali.vm.box = "kalilinux/rolling"
    kali.vm.hostname = "external-kali"
    kali.vm.box_check_update=false
    
    # Red externa - SOLO interna
    kali.vm.network "private_network", ip: "100.70.9.10", 
      virtualbox__intnet: "net-externa"
    
    #Puerto para noVNC y poder acceder desde http://localhost:8081
    kali.vm.network "forwarded_port", guest: 8080, host: 8081
    
    kali.vm.provider "virtualbox" do |vb|
      vb.name = "external-kali-mv"
      vb.memory = 2560
      vb.cpus = 2
      vb.gui = false
      vb.customize ["modifyvm", :id, "--audio", "none"]
      vb.customize ["modifyvm", :id, "--usb", "off"]
      vb.customize ["modifyvm", :id, "--vram", "16"]
      # Desactivar promiscuo en la interfaz de gestión
      vb.customize ["modifyvm", :id, "--nicpromisc1", "deny"]
      # Permitir en la red de laboratorio
      vb.customize ["modifyvm", :id, "--nicpromisc2", "allow-all"]
      # Desactivar NAT DNS
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "off"]
      vb.customize ["modifyvm", :id, "--natdnsproxy1", "off"]
    end
    
    kali.vm.provision "shell", path: "scripts/external-kali/setup.sh", 
      privileged: true
    kali.vm.provision "shell", path: "scripts/external-kali/gui.sh", 
      privileged: true
  end

  # Máquina virtual del servidor de la red interna
  config.vm.define "internal-server" do |internal|
    internal.vm.box = "ubuntu/jammy64"
    internal.vm.hostname = "internal-server"
    
    internal.vm.network "private_network", ip: "192.168.58.10", 
      virtualbox__intnet: "net-interna"
    
    internal.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
      vb.cpus = 1
      vb.name = "insecure-internal-vm"
      vb.customize ["modifyvm", :id, "--nicpromisc1", "deny"]
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "off"]
    end
    
    internal.vm.provision "shell", path: "scripts/internal-server/setup.sh", 
      privileged: true
    internal.vm.provision "shell", path: "scripts/internal-server/data.sh", 
      privileged: true
  end

  # Máquina virtual para el firewall vulnerable
  config.vm.define "firewall" do |fw|
    fw.vm.box = "ubuntu/jammy64"
    fw.vm.hostname = "firewall"
    
    # Interfaces de red - IMPORTANTE: nictype explícito
    fw.vm.network "private_network", ip: "100.70.9.1", 
      virtualbox__intnet: "net-externa", nic_type: "82540EM"
    
    fw.vm.network "private_network", ip: "192.168.57.1", 
      virtualbox__intnet: "net-dmz", nic_type: "82540EM"
    
    fw.vm.network "private_network", ip: "192.168.58.1", 
      virtualbox__intnet: "net-interna", nic_type: "82540EM"
    
    fw.vm.provider "virtualbox" do |vb|
      vb.memory = 512
      vb.cpus = 1
      vb.name = "insecure-firewall"
      vb.customize ["modifyvm", :id, "--nicpromisc1", "deny"]
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "off"]
    end
    
    fw.vm.provision "shell", path: "scripts/firewall/setup.sh"
  end

  # Máquina virtual para el servidor DMZ
  config.vm.define "dmz-server" do |dmz|
    dmz.vm.box = "ubuntu/jammy64"
    dmz.vm.hostname = "dmz-server"
    
    dmz.vm.network "private_network", ip: "192.168.57.10", 
      virtualbox__intnet: "net-dmz"
    
    dmz.vm.provider "virtualbox" do |vb|
      vb.memory = 512
      vb.cpus = 1
      vb.name = "dmz-server-vm"
      vb.customize ["modifyvm", :id, "--nicpromisc1", "deny"]
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "off"]
    end
    
    dmz.vm.provision "shell", path: "scripts/dmz-server/setup.sh", 
      privileged: true
    dmz.vm.provision "shell", path: "scripts/dmz-server/config.sh", 
      privileged: true
    dmz.vm.provision "shell", path: "scripts/dmz-server/phishing.sh", 
      privileged: true
  end
end