Vagrant.configure("2") do |config|

  config.vm.define "opensense" do |fw|
    fw.vm.box = "snl-opnsense"

    # OPNsense no usa SSH de Vagrant.
    fw.vm.network "forwarded_port",
      guest: 22, host: 2200,
      host_ip: "127.0.0.1",
      id: "ssh",
      disabled: true

    fw.ssh.insert_key = false

    # em1 — WAN simulada (red interna, solo entre VMs)
    fw.vm.network "private_network",
      virtualbox__intnet: "net-wan",
      auto_config: false

    # em2 — LAN trunk (VLANs 10/20/30)
    fw.vm.network "private_network",
      virtualbox__intnet: "net-lan",
      auto_config: false

    # em3 — DMZ
    fw.vm.network "private_network",
      virtualbox__intnet: "net-dmz",
      auto_config: false

    # em4 — Gestión host-only (WebUI durante desarrollo)
    fw.vm.network "private_network",
      ip: "192.168.56.10",
      netmask: "255.255.255.0"

    fw.vm.provider "virtualbox" do |vb|
      vb.name   = "snl-opensense"
      vb.memory = 1024
      vb.cpus   = 1
      vb.gui    = false
    end
    fw.vm.boot_timeout = 10
    fw.ssh.connect_timeout = 5
  end

end