Vagrant.configure("2") do |config|
  config.vm.box_check_update = false

  # OPNsense Firewall
  # Orden de interfaces (importante para configurar en WebUI):
  #   em0 → NAT implícita de Vagrant (no tocar)
  #   em1 → net-wan      → WAN (91.168.50.1)
  #   em2 → net-dmz      → DMZ (172.16.0.1)
  #   em3 → net-gestion  → VLAN10 Gestión (192.168.10.1)
  #   em4 → net-lan      → VLAN20 Servidores (192.168.20.1)
  #   em5 → host-only    → Gestión temporal desarrollo (192.168.56.10)
  config.vm.define "opensense" do |fw|
    fw.vm.box = "snl-opensense/snl-opensense-configured"    fw.vm.box_url = "https://github.com/JohanV711/TSI-TFG/releases/download/v2.0.0/opnsense-25.1-lab-configured.box"
    fw.vm.network "forwarded_port",
      guest: 22, host: 2200,
      host_ip: "127.0.0.1",
      id: "ssh",
      disabled: true

    fw.ssh.insert_key = false

    # em1 — WAN
    fw.vm.network "private_network",
      virtualbox__intnet: "net-wan",
      auto_config: false

    # em2 — DMZ
    fw.vm.network "private_network",
      virtualbox__intnet: "net-dmz",
      auto_config: false

    # em3 — VLAN10 Gestión
    fw.vm.network "private_network",
      virtualbox__intnet: "net-gestion",
      auto_config: false

    # em4 — VLAN20 Servidores
    fw.vm.network "private_network",
      virtualbox__intnet: "net-lan",
      auto_config: false

    fw.vm.provider "virtualbox" do |vb|
      vb.name   = "snl-opensense"
      vb.memory = 1500
      vb.cpus   = 1
      vb.gui    = false
      vb.customize ["modifyvm", :id, "--audio", "none"]
      vb.customize ["modifyvm", :id, "--usb", "off"]
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "off"]
      vb.customize ["modifyvm", :id, "--natdnsproxy1", "off"]
    end

    fw.vm.boot_timeout    = 10
    fw.ssh.connect_timeout = 5
  end

  # External Kali — atacante simulado en WAN
  # IP: 91.168.50.10
  # Acceso navegador via noVNC: http://localhost:6080/vnc.html
  config.vm.define "external-kali" do |kali|
    kali.vm.box          = "kalilinux/rolling"
    kali.vm.hostname     = "external-kali"
    kali.vm.boot_timeout = 600

    kali.vm.network "private_network",
      ip:                  "91.168.50.10",
      virtualbox__intnet:  "net-wan",
      nic_type:            "82540EM"

    #para navegador con interfaz gráfica, dentro del host escuchará en 6080.
    kali.vm.network "forwarded_port", guest: 8081, host: 8081

    kali.vm.provider "virtualbox" do |vb|
      vb.name   = "snl-external-kali"
      vb.memory = 2560
      vb.cpus   = 2
      vb.gui    = false
      vb.customize ["modifyvm", :id, "--audio",             "none"]
      vb.customize ["modifyvm", :id, "--usb",               "off"]
      vb.customize ["modifyvm", :id, "--vram",              "16"]
      vb.customize ["modifyvm", :id, "--nicpromisc2",       "allow-all"]
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "off"]
      vb.customize ["modifyvm", :id, "--natdnsproxy1",      "off"]
    end

    kali.vm.provision "shell", path: "scripts/external-kali/setup.sh", privileged: true
    kali.vm.provision "shell", path: "scripts/external-kali/gui.sh", privileged: true
  end

  # DMZ Server — servidor web público
  # IP: 172.16.0.10
  config.vm.define "dmz-server" do |dmz|
    dmz.vm.box          = "ubuntu/jammy64"
    dmz.vm.hostname     = "dmz-server"
    dmz.vm.boot_timeout = 600

    dmz.vm.network "private_network",
      ip:                 "172.16.0.10",
      virtualbox__intnet: "net-dmz",
      nic_type:           "82540EM"

    dmz.vm.provider "virtualbox" do |vb|
      vb.name   = "snl-dmz-server"
      vb.memory = 612
      vb.cpus   = 1
      vb.gui    = false
      vb.customize ["modifyvm", :id, "--audio",             "none"]
      vb.customize ["modifyvm", :id, "--usb",               "off"]
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "off"]
      vb.customize ["modifyvm", :id, "--natdnsproxy1",      "off"]
    end

    dmz.vm.provision "shell", path: "scripts/dmz-server/setup.sh", privileged: true
  end

  # VLAN20 Servidores — MySQL con datos sensibles
  # IP: 192.168.20.10
  config.vm.define "vlan20-server" do |srv|
    srv.vm.box          = "ubuntu/jammy64"
    srv.vm.hostname     = "vlan20-server"
    srv.vm.boot_timeout = 600

    srv.vm.network "private_network",
      ip:                 "192.168.20.10",
      virtualbox__intnet: "net-lan",
      nic_type:           "82540EM"

    srv.vm.provider "virtualbox" do |vb|
      vb.name   = "snl-vlan20-server"
      vb.memory = 612
      vb.cpus   = 1
      vb.gui    = false
      vb.customize ["modifyvm", :id, "--audio",             "none"]
      vb.customize ["modifyvm", :id, "--usb",               "off"]
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "off"]
      vb.customize ["modifyvm", :id, "--natdnsproxy1",      "off"]
    end

    srv.vm.provision "shell", path: "scripts/vlan20-server/setup.sh", privileged: true
  end

end