up:
	chmod +x db/01_init.sh
	sudo docker compose up --build -d

down:
	sudo docker compose down

stop:
	sudo docker compose stop

reset:
	sudo docker compose down -v

logs: 
	sudo docker compose logs -f
