services:
  db:
      image: postgres:16
      volumes:
        - ./db/01_init.sh:/docker-entrypoint-initdb.d/01_init.sh
        - ./db/02_init.sql:/docker-entrypoint-initdb.d/02_init.sql
        - postgres_data:/var/lib/postgresql/data
      env_file:
        - .env 
      networks:
        - app_net
      #No se ponen ports porque la BD no va a ser accesible desde el exterior.

  backend:
    build: ./backend
    ports:
      - "8000:8000" #SÓLO PARA DESARROLLO, quitarlo cuando se termine.
    volumes:
      - uploads_data:/app/uploads
      - ./backend/app:/app/app #SÓLO PARA DESARROLLO, para que se reflejen los cambios que se hagan en backend/app directamente dentro del contenedor.
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - app_net

networks:
  app_net:
    driver: bridge

volumes:
  postgres_data:
  uploads_data: