services:
  db:
      image: postgres:16
      volumes:
        - ./db/01_init.sh:/docker-entrypoint-initdb.d/01_init.sh
        - ./db/02_init.sql:/docker-entrypoint-initdb.d/02_init.sql
        - postgres_data:/var/lib/postgresql/data
      env_file:
        - .env 
      networks:
        - app_net
      #No se ponen ports porque la BD no va a ser accesible desde el exterior.

  backend:
    build: ./backend
    volumes:
      - uploads_data:/app/uploads
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - app_net

  frontend-build: #Este contenedor no arranca, solo construye el build del frontend.
    build: ./frontend
    image: frontend-build
    command: echo "Build completado"

  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    ports:
      - "80:80"
      - "443:443"
    depends_on: 
      - backend
      - frontend-build
    networks:
      - app_net

networks:
  app_net:
    driver: bridge

volumes:
  postgres_data:
  uploads_data: