name: Limpieza de Workflows

on:
  workflow_dispatch:   

jobs:
  limpiar:
    runs-on: ubuntu-latest
    permissions:
      actions: write    #Permiso obligatorio para poder eliminar historiales

    steps:
      - name: Clean workflow runs
        uses: dmvict/clean-workflow-runs@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          save_period: 0           # No depende de los días de antigüedad.
          save_min_runs_number: 3
