#Auditoría de seguridad automática del bloque 1, 1-secure-app.
#Escanea imágenes de Docker en busca de vulnerabilidades, secretos expuestos en el código y que los 
#Dockerfiles sigan buenas prácticas.

name: Security audit

on: 
  workflow_dispatch:      #Para ejecutar este workflow cuando quiera.
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: "0 8 * * *" # todos los días a las 8:00 hora de Madrid, aunque no haya push.

jobs:

  trivy:      #construye imágenes de backend y frontend y luego las escanea buscando CVEs graves o críticas.
    name: Trivy - escaneo de vulnerabilidades CVE # Un CVE (Common Vulnerabilities and Exposures o Vulnerabilidades y Exposiciones Comunes) 
                                                  #es un catálogo público y estandarizado que identifica fallos de seguridad conocidos en programas y 
                                                  #equipos informáticos
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4      #descarga el código del repositorio dentro de la MV de GitHub donde se ejcuta el flujo de trabajo.

      - name: Build de imagen backend para escanear
        working-directory: 1-secure-app
        run: docker build -t tfg-backend:scan backend/.

      - name: Trivy informe general
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: tfg-backend:scan
          format: table
          severity: UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL
          exit-code: "0"
      
      - name: Trivy bloquear solo grave
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: tfg-backend:scan
          format: table
          severity: HIGH,CRITICAL
          exit-code: "0"
          ignore-unfixed: true

      # - name: Build imagen frontend para escanear
      #  working-directory: 1-secure-app
      #  run: docker build -t tfg-frontend:scan frontend/

      # - name: Escanear imagen frontend
      #   uses: aquasecurity/trivy-action@master
      #   with:
      #     image-ref: tfg-frontend:scan
      #     format: table
      #     severity: HIGH,CRITICAL
      #     exit-code: "1"      

  gitleaks:      #revisa el repositorio para detectar secretos como tokens, claves o contraseñas.
    name: Gitleaks - detección de secrets en el código
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Escanear secrets con gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  hadolint:        #analiza tus Dockerfiles para encontrar patrones malos o peligrosos.
    name: Hadolint - buenas prácticas en Dockerfiles
    runs-on: ubuntu-latest
    strategy: 
      matrix:
        dockerfile:
          - 1-secure-app/backend/Dockerfile
          # - 1-secure-app/frontend/Dockerfile
          # - 1- secure-app/nginx/Dockerfile
    steps:
      - uses: actions/checkout@v4
      - name: Lint ${{ matrix.dockerfile }}
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: ${{ matrix.dockerfile }}
          failure-threshold: warning
          
